FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-training.txt .
RUN pip install --no-cache-dir -r requirements-training.txt

COPY train.py .
COPY prepare_dataset.py .

CMD ["python", "train.py"]
